[2023-04-10 16:41:10,571][moc][INFO][color_logger.py:203] Logfile: /home/chenyiqi/wafer_scale_chip_dse_framework/logs/moc_2023-04-10-16-41-10-571440.log
[2023-04-10 16:41:10,572][moc][WARNING][generic_smbo.py:387] Exception when calling objective function: local variable '_history' referenced before assignment
config: Configuration(values={
  'fidelity': 1,
  'var00': 48,
  'var01': 1024,
  'var02': 8,
  'var03': 128,
  'var04': 4,
  'var05': 4,
  'var06': 1,
  'var07': 16,
  'var08': 32,
  'var09': 900,
  'var10': 19,
  'var11': 17,
})

[2023-04-10 16:41:10,572][moc][INFO][generic_smbo.py:418] Iter 14, objectives: [inf].
[2023-04-10 16:41:10,572][moc][WARNING][mf_advisor.py:421] No enough successful initial trials! Sample random configuration.
[2023-04-10 16:41:10,574][moc][WARNING][util_funcs.py:231] Keyword argument "num_objs" is deprecated and will be removed in a future version. Please use "num_objectives" instead.
